{% set name = "CppInterOp" %}
{% set build_number = 0 %}
{% set version = "1.2.0" %}
{% set revision_tag = "v"+version %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/compiler-research/CppInterOp/archive/refs/tags/{{ revision_tag }}.tar.gz
    sha256: b3cf25f500624fe12ffc40f858a04c46daea808298e64d924b594eb35ca1c806
    folder: cppinterop
    patches:
      - patches/cppinterop/0001-cmake-Work-around-a-bug-in-the-llvm-config.patch
  - path: patches
    folder: add_patches

build:
  number: {{ build_number }}
  string: clang{{ (clangdev or "None").split(".")[0] }}_repl_h{{ PKG_HASH }}_{{ build_number }}

requirements:
  build:
    - cmake
    #- clang  # [osx]
    - make  # [unix]
    - ninja  # [win]
    - {{ compiler('cxx') }}
    - llvm {{ clangdev }}
    - llvmdev {{ clangdev }}
    - clangdev {{ clangdev }}
    - git-lfs
    - libcxx {{ cxx_compiler_version }}  # [osx]
    - libstdcxx-ng {{ cxx_compiler_version }}  # [linux]
  host:
    - llvm {{ clangdev }}
    - llvmdev {{ clangdev }}
    - clangdev {{ clangdev }}
    - backtrace  # [unix and x86]
    - libxml2
    - zlib
    - zstd  # [not win]
    - libcxx {{ cxx_compiler_version }}  # [osx]
    - libstdcxx-ng {{ cxx_compiler_version }}  # [linux]
  run_constrained:
    - llvm {{ clangdev }}
    - llvmdev {{ clangdev }}
    - clangdev {{ clangdev }}
  run:
    - libcxx {{ cxx_compiler_version }}  # [osx]
    - libstdcxx-ng >={{ cxx_compiler_version }}  # [linux]

test:
  commands:
    - test -f $PREFIX/lib/libclangCppInterOp${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_BIN%\\clangCppInterOp.dll exit 1  # [win]

about:
  home: https://github.com/compiler-research/CppInterOp
  license: Apache-2.0 WITH LLVM-exception
  license_family: Apache
  license_file: cppinterop/LICENSE.txt
  summary: |
    The CppInterOp library provides a minimalist approach for other languages
    to interoperate with C++ entities.
  description: |
    CppInterOp exposes API from Clang and LLVM in a backward compatibe way.
    The API support downstream tools that utilize interactive C++ by using
    the compiler as a service. That is, embed Clang and LLVM as a libraries
    in their codebases. The API are designed to be minimalistic and aid
    non-trivial tasks such as language interoperability on the fly. In such
    scenarios CppInterOp can be used to provide the necessary introspection
    information to the other side helping the language cross talk.
  doc_url: https://cppinterop.readthedocs.io/en/{{ version }}
  dev_url: https://cppinterop.readthedocs.io/en/{{ version }}/DevelopersDocumentation.html

extra:
  recipe-maintainers:
    - alexander-penev
    - vgvassilev
